#!/usr/bin/env node
// Regenerate THIRD-PARTY-NOTICES.txt from what actually ships.
//
//   npm run notices
//
// Sojourn distributes other people's code: bundled into the client JS, into the
// server build, and into the Docker image. Nearly every one of those licences —
// MIT, BSD, ISC, Apache-2.0 — permits that only on the condition that their
// copyright notice travels with it. Minification strips those banners, so
// without this file the condition is simply not met.
//
// Generated, not written, because a hand-maintained list is wrong the first
// time a dependency changes and nobody can tell by looking. `npm run notices`
// after any dependency change; test/unit/notices.test.ts fails if it drifts.
import { readFileSync, writeFileSync, readdirSync, existsSync } from "node:fs";
import { join } from "node:path";

const LICENSE_FILE = /^(LICEN[CS]E|COPYING|NOTICE)($|[.-])/i;

/**
 * Every production dependency, read from package-lock.json.
 *
 * Straight from the lockfile rather than out of `npm ls`: no subprocess (which
 * Node will not spawn for npm.cmd on Windows without a shell), no network, and
 * the same answer on every machine. The lockfile marks dev-only packages with
 * `dev: true` — everything else is installed for production and therefore ships.
 */
function productionTree() {
  const lock = JSON.parse(readFileSync("package-lock.json", "utf8"));
  if (!lock.packages) {
    throw new Error(
      `package-lock.json is lockfileVersion ${lock.lockfileVersion}; this needs v2 or later (npm 7+).`,
    );
  }
  const found = [];
  for (const [path, entry] of Object.entries(lock.packages)) {
    // "" is the root project itself — our own code, not a third party.
    if (!path.startsWith("node_modules/") || entry.dev) continue;
    found.push({
      name: path.slice(path.lastIndexOf("node_modules/") + "node_modules/".length),
      version: entry.version ?? "?",
      path,
    });
  }
  return found.sort(
    (a, b) => a.name.localeCompare(b.name) || a.version.localeCompare(b.version),
  );
}

/** The package's own licence text, which is the part that must travel. */
function licenseText(dir) {
  if (!existsSync(dir)) return null;
  const file = readdirSync(dir).find((f) => LICENSE_FILE.test(f));
  if (!file) return null;
  try {
    const text = readFileSync(join(dir, file), "utf8").trim();
    return text.length > 0 ? text : null;
  } catch {
    return null;
  }
}

function meta(dir) {
  try {
    const p = JSON.parse(readFileSync(join(dir, "package.json"), "utf8"));
    const license =
      typeof p.license === "string"
        ? p.license
        : (p.license?.type ??
          (Array.isArray(p.licenses)
            ? p.licenses.map((l) => l.type ?? l).join(" OR ")
            : null));
    const url =
      typeof p.repository === "string"
        ? p.repository
        : (p.repository?.url ?? p.homepage ?? null);
    return { license: license ?? "UNKNOWN", url: (url ?? "").replace(/^git\+|\.git$/g, "") };
  } catch {
    return { license: "UNKNOWN", url: "" };
  }
}

const pkgs = productionTree().map((p) => ({ ...p, ...meta(p.path), text: licenseText(p.path) }));

// Group by exact licence text. Identical texts collapse; anything differing by
// so much as a copyright holder stays separate, which is the whole point.
const groups = new Map();
for (const p of pkgs) {
  if (!p.text) continue;
  const g = groups.get(p.text) ?? [];
  g.push(p);
  groups.set(p.text, g);
}
const noText = pkgs.filter((p) => !p.text);

const out = [];
out.push(
  "THIRD-PARTY NOTICES FOR SOJOURN",
  "",
  "Sojourn is licensed under the GNU AGPL-3.0-only (see LICENSE). It bundles and",
  "redistributes the third-party software listed below, each under its own terms.",
  "Those terms are reproduced here in full, which is what most of them require in",
  "exchange for redistribution.",
  "",
  "Generated by `npm run notices` from the production dependency tree — do not",
  `edit by hand. ${pkgs.length} packages.`,
  "",
  "".padEnd(78, "="),
  "SOFTWARE NOT INSTALLED BY npm",
  "".padEnd(78, "="),
  "",
  "libvips — LGPL-3.0-or-later — https://github.com/libvips/libvips",
  "  The Docker image and Vercel builds include `sharp`, whose prebuilt binaries",
  "  embed libvips. libvips is licensed under the LGPL-3.0-or-later. Its complete",
  "  source is available from the URL above; you may modify and relink it, and",
  "  the prebuilt binaries in `node_modules/sharp` are the object form of that",
  "  library as shipped.",
  "",
  "Inter and Fraunces (typefaces) — SIL Open Font License 1.1",
  "  Fetched and self-hosted at build time by next/font/google. Both are licensed",
  "  under the SIL OFL 1.1: https://openfontlicense.org",
  "  Inter — https://github.com/rsms/inter",
  "  Fraunces — https://github.com/undercasetype/Fraunces",
  "",
  "Map tiles, styles and geodata are fetched at runtime from whichever provider a",
  "deployment configures; they are not redistributed with this software and carry",
  "their own terms (OpenStreetMap data is ODbL).",
  "",
  "".padEnd(78, "="),
  "INSTALLED PACKAGES",
  "".padEnd(78, "="),
  "",
);

for (const p of pkgs) {
  out.push(`${p.name}@${p.version} — ${p.license}${p.url ? ` — ${p.url}` : ""}`);
}
out.push("", "".padEnd(78, "="), "LICENSE TEXTS", "".padEnd(78, "="), "");

// Longest first: the substantial licences (Apache, BSD with attribution) lead,
// rather than opening on whichever package happens to sort first.
const ordered = [...groups.entries()].sort((a, b) => b[1].length - a[1].length);
for (const [text, members] of ordered) {
  out.push("".padEnd(78, "-"));
  out.push(`Applies to: ${members.map((m) => `${m.name}@${m.version}`).join(", ")}`);
  out.push("".padEnd(78, "-"), "", text, "");
}

if (noText.length > 0) {
  out.push(
    "".padEnd(78, "="),
    "PACKAGES SHIPPING NO LICENSE FILE",
    "".padEnd(78, "="),
    "",
    "These declare a licence in package.json but ship no licence file of their own.",
    "The declared identifier governs; the canonical text is at https://spdx.org/licenses/.",
    "",
  );
  for (const p of noText) {
    out.push(`${p.name}@${p.version} — ${p.license}${p.url ? ` — ${p.url}` : ""}`);
  }
  out.push("");
}

writeFileSync("THIRD-PARTY-NOTICES.txt", out.join("\n"));
console.error(
  `THIRD-PARTY-NOTICES.txt: ${pkgs.length} packages, ${groups.size} distinct licence texts, ${noText.length} without a licence file`,
);
