// @ts-check
// NOTE: no shebang — see scripts/strip-prerender.mjs for why.
//
// Mint the secrets an all-in-one deployment needs, once.
//
//   node scripts/selfhost-init.mjs [--force]     # writes ./.env.selfhost, 0600
//   node scripts/selfhost-init.mjs --stdout      # writes it to stdout instead
//
// `--stdout` exists so this can be run straight out of the published image,
// which is the whole point of it being in there: self-hosting should not begin
// with cloning a repository whose source you never need.
//
//   docker run --rm ghcr.io/galgtonold/sojourn:latest \
//     node scripts/selfhost-init.mjs --stdout > .env.selfhost
//
// Progress and warnings go to stderr, so a redirect of stdout captures exactly
// the file and nothing else.
//
// Supabase's own services authenticate each other with JWTs signed by a shared
// secret. Self-hosting means minting those yourself, and getting it wrong is
// not loud: a service_role key signed with the wrong secret fails as "invalid
// claim", which reads like a bug in the app. So this does it in one place, from
// one secret, and writes a file the compose stack reads whole.
//
// Everything here is per-instance and must never be shared, committed, or
// copied from a tutorial — a well-known JWT secret means anyone can mint
// themselves a service_role token and read the entire database.
import { createHmac, randomBytes } from "node:crypto";
import { existsSync, writeFileSync } from "node:fs";

const OUT = ".env.selfhost";

/** URL-safe base64 with the padding stripped, which is what JWT wants. */
function b64url(input) {
  return Buffer.from(input).toString("base64url");
}

/**
 * A signed HS256 JWT. Supabase's services want exactly this shape: a `role`
 * claim naming the Postgres role to assume, and a long expiry (these are
 * infrastructure keys, not sessions).
 *
 * @param {{ role: string, iat: number, exp: number }} claims
 * @param {string} secret
 * @returns {string}
 */
function signJwt(claims, secret) {
  const header = b64url(JSON.stringify({ alg: "HS256", typ: "JWT" }));
  const payload = b64url(JSON.stringify({ iss: "supabase", ...claims }));
  const data = `${header}.${payload}`;
  const sig = createHmac("sha256", secret).update(data).digest("base64url");
  return `${data}.${sig}`;
}

/** Alphanumeric only: this ends up in URLs, YAML and shell, unquoted. */
function secret(bytes) {
  return randomBytes(bytes).toString("base64").replace(/[^a-zA-Z0-9]/g, "").slice(0, bytes);
}

const toStdout = process.argv.includes("--stdout");

// Only meaningful when we are the one doing the writing. Under --stdout the
// caller owns the destination, and inside a container there is nothing at OUT
// to protect anyway.
if (!toStdout && existsSync(OUT) && !process.argv.includes("--force")) {
  console.error(
    `${OUT} already exists — refusing to overwrite.\n` +
      `Re-running would mint a new JWT secret, which invalidates every existing\n` +
      `session and orphans the data in your database. Pass --force only if you\n` +
      `mean exactly that.`,
  );
  process.exit(1);
}

// Ten years. These are not sessions; rotating them means restarting the stack,
// so an expiry short enough to be a security feature is just an outage.
const iat = Math.floor(Date.now() / 1000);
const exp = iat + 10 * 365 * 24 * 60 * 60;

const jwtSecret = secret(48);
const env = {
  POSTGRES_PASSWORD: secret(32),
  JWT_SECRET: jwtSecret,
  SUPABASE_ANON_KEY: signJwt({ role: "anon", iat, exp }, jwtSecret),
  SUPABASE_SERVICE_KEY: signJwt({ role: "service_role", iat, exp }, jwtSecret),
};

const file = `# Generated by \`node scripts/selfhost-init.mjs\` — per-instance secrets.
#
# NEVER commit this, and never copy it from anywhere. The JWT secret below is
# what lets Supabase's services trust each other; anyone holding it can mint a
# service_role token and read your whole database.
#
# Back it up somewhere safe. Losing it does not lose your posts, but it does
# mean re-minting every key and signing everyone out.

POSTGRES_PASSWORD=${env.POSTGRES_PASSWORD}
JWT_SECRET=${env.JWT_SECRET}
SUPABASE_ANON_KEY=${env.SUPABASE_ANON_KEY}
SUPABASE_SERVICE_KEY=${env.SUPABASE_SERVICE_KEY}

# ── things you should change ─────────────────────────────────────────────────
#
# The URL BROWSERS use to reach Supabase — it is handed to the visitor's
# JavaScript, so "localhost" only works if you are the only visitor. It must
# also be reachable from the app container, which is why the default is
# host.docker.internal rather than localhost: the container cannot reach its own
# loopback to find Kong.
#
# CHANGE THE SCHEME TOO, not just the host. Everything the browser sends to
# Supabase goes over this URL — including the password you sign in with and the
# session token every request afterwards carries. Over http:// on a real host
# that is all readable by anyone on the path. Put a TLS-terminating proxy in
# front and use its https:// address. The app warns about this in its logs at
# start-up, but it will not stop you.
SUPABASE_PUBLIC_URL=http://host.docker.internal:8000

# Where readers reach Sojourn itself.
SITE_URL=http://localhost:3000
SITE_NAME=Sojourn

# Optional. Drafting, proofreading and translation need this; everything else
# works without it.
# DEEPSEEK_API_KEY=

# Set this if you modify the code — AGPL §13 asks you to point your readers at
# the source of the version they are using.
# SOURCE_URL=https://git.example.org/you/sojourn
`;

if (toStdout) {
  process.stdout.write(file);
  // The shell's umask decides the mode of a redirect, and the usual answer is
  // 0644 — world-readable, which for this file is the whole database. We cannot
  // chmod a file we never opened, so say so where it will be read.
  console.error(
    `Minted a Postgres password, a JWT secret and the anon/service_role keys.\n` +
      `If you redirected this to a file, lock it down now — the default mode is\n` +
      `world-readable and this holds the secret every service trusts:\n` +
      `  chmod 600 ${OUT}\n` +
      `Then edit SUPABASE_PUBLIC_URL and SITE_URL for your host and bring it up.`,
  );
} else {
  // 0600: this holds the JWT secret every service trusts and the Postgres
  // password. The default would be world-readable, which on a shared host is
  // the whole database.
  writeFileSync(OUT, file, { mode: 0o600 });
  console.error(
    `Wrote ${OUT}: Postgres password, JWT secret and the anon/service_role keys.\n` +
      `Edit SUPABASE_PUBLIC_URL and SITE_URL for your host, then:\n` +
      `  docker compose -f docker-compose.all-in-one.yml --env-file ${OUT} up -d`,
  );
}
