// @ts-check
// NOTE: no shebang — see scripts/strip-prerender.mjs for why.
//
// Mint the secrets an all-in-one deployment needs, once.
//
//   node scripts/selfhost-init.mjs [--force]
//
// Supabase's own services authenticate each other with JWTs signed by a shared
// secret. Self-hosting means minting those yourself, and getting it wrong is
// not loud: a service_role key signed with the wrong secret fails as "invalid
// claim", which reads like a bug in the app. So this does it in one place, from
// one secret, and writes a file the compose stack reads whole.
//
// Everything here is per-instance and must never be shared, committed, or
// copied from a tutorial — a well-known JWT secret means anyone can mint
// themselves a service_role token and read the entire database.
import { createHmac, randomBytes } from "node:crypto";
import { existsSync, writeFileSync } from "node:fs";

const OUT = ".env.selfhost";

/** URL-safe base64 with the padding stripped, which is what JWT wants. */
function b64url(input) {
  return Buffer.from(input).toString("base64url");
}

/**
 * A signed HS256 JWT. Supabase's services want exactly this shape: a `role`
 * claim naming the Postgres role to assume, and a long expiry (these are
 * infrastructure keys, not sessions).
 *
 * @param {{ role: string, iat: number, exp: number }} claims
 * @param {string} secret
 * @returns {string}
 */
function signJwt(claims, secret) {
  const header = b64url(JSON.stringify({ alg: "HS256", typ: "JWT" }));
  const payload = b64url(JSON.stringify({ iss: "supabase", ...claims }));
  const data = `${header}.${payload}`;
  const sig = createHmac("sha256", secret).update(data).digest("base64url");
  return `${data}.${sig}`;
}

/** Alphanumeric only: this ends up in URLs, YAML and shell, unquoted. */
function secret(bytes) {
  return randomBytes(bytes).toString("base64").replace(/[^a-zA-Z0-9]/g, "").slice(0, bytes);
}

if (existsSync(OUT) && !process.argv.includes("--force")) {
  console.error(
    `${OUT} already exists — refusing to overwrite.\n` +
      `Re-running would mint a new JWT secret, which invalidates every existing\n` +
      `session and orphans the data in your database. Pass --force only if you\n` +
      `mean exactly that.`,
  );
  process.exit(1);
}

// Ten years. These are not sessions; rotating them means restarting the stack,
// so an expiry short enough to be a security feature is just an outage.
const iat = Math.floor(Date.now() / 1000);
const exp = iat + 10 * 365 * 24 * 60 * 60;

const jwtSecret = secret(48);
const env = {
  POSTGRES_PASSWORD: secret(32),
  JWT_SECRET: jwtSecret,
  SUPABASE_ANON_KEY: signJwt({ role: "anon", iat, exp }, jwtSecret),
  SUPABASE_SERVICE_KEY: signJwt({ role: "service_role", iat, exp }, jwtSecret),
};

const file = `# Generated by \`node scripts/selfhost-init.mjs\` — per-instance secrets.
#
# NEVER commit this, and never copy it from anywhere. The JWT secret below is
# what lets Supabase's services trust each other; anyone holding it can mint a
# service_role token and read your whole database.
#
# Back it up somewhere safe. Losing it does not lose your posts, but it does
# mean re-minting every key and signing everyone out.

POSTGRES_PASSWORD=${env.POSTGRES_PASSWORD}
JWT_SECRET=${env.JWT_SECRET}
SUPABASE_ANON_KEY=${env.SUPABASE_ANON_KEY}
SUPABASE_SERVICE_KEY=${env.SUPABASE_SERVICE_KEY}

# ── things you should change ─────────────────────────────────────────────────
#
# The URL BROWSERS use to reach Supabase — it is handed to the visitor's
# JavaScript, so "localhost" only works if you are the only visitor. On a real
# host this is your domain or IP, and it must also be reachable from the app
# container (which is why the default below is host.docker.internal rather than
# localhost: the container cannot reach its own loopback to find Kong).
SUPABASE_PUBLIC_URL=http://host.docker.internal:8000

# Where readers reach Sojourn itself.
SITE_URL=http://localhost:3000
SITE_NAME=Sojourn

# Optional. Drafting, proofreading and translation need this; everything else
# works without it.
# DEEPSEEK_API_KEY=

# Set this if you modify the code — AGPL §13 asks you to point your readers at
# the source of the version they are using.
# SOURCE_URL=https://git.example.org/you/sojourn
`;

writeFileSync(OUT, file);
console.error(
  `Wrote ${OUT}: Postgres password, JWT secret and the anon/service_role keys.\n` +
    `Edit SUPABASE_PUBLIC_URL and SITE_URL for your host, then:\n` +
    `  docker compose -f docker-compose.all-in-one.yml --env-file ${OUT} up -d`,
);
